### ISSUE TITLE
Installation not possible because of missing module regex

### ISSUE THREAD

**Issue by 1kastner** [ppannuto/python-titlecase#50]
```
(base) PS C:\XXX\titlecase> python setup.py install --user   
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from titlecase import __version__
  File "C:\XXX\titlecase\titlecase\__init__.py", line 19, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'
(base) PS C:\XXX\titlecase> 
```

The version should be kept somewhere else!

**Comment by ppannuto** [comment]
Closed by #55 (really #54, thanks again @iburago!)
